INSERT INTO TB_USUARIO (nome, email, senha) VALUES ('Marcos Pinho', 'marcos.pinho@investinfo.com.br', '1111')
INSERT INTO TB_USUARIO (nome, email, senha) VALUES ('Lucas Borges', 'lucas.bordes@investinfo.com.br', '2222')
INSERT INTO TB_USUARIO (nome, email, senha) VALUES ('Gabriel Ribeiro', 'gabriel.ribeiro@investinfo.com.br', '3333')
INSERT INTO TB_USUARIO (nome, email, senha) VALUES ('Gabriel Maia', 'gabriel.maia@investinfo.com.br', '4444')
INSERT INTO TB_USUARIO (nome, email, senha) VALUES ('Gustavo Merhey', 'gustavo.merhey@investinfo.com.br', '5555')
INSERT INTO TB_USUARIO (nome, email, senha) VALUES ('Leonardo Pimentel', 'leonardo.pimentel@investinfo.com.br', '6666')
INSERT INTO TB_USUARIO (nome, email, senha) VALUES ('Vanderlei Junior', 'vanderlei.junior@investinfo.com.br', '7777')