INSERT INTO TB_USER (name, email, password) VALUES ('Marcos Pinho', 'marcos.pinho@investinfo.com.br', '1111')
INSERT INTO TB_USER (name, email, password) VALUES ('Lucas Borges', 'lucas.bordes@investinfo.com.br', '2222')
INSERT INTO TB_USER (name, email, password) VALUES ('Gabriel Ribeiro', 'gabriel.ribeiro@investinfo.com.br', '3333')
INSERT INTO TB_USER (name, email, password) VALUES ('Gabriel Maia', 'gabriel.maia@investinfo.com.br', '4444')
INSERT INTO TB_USER (name, email, password) VALUES ('Gustavo Merhey', 'gustavo.merhey@investinfo.com.br', '5555')
INSERT INTO TB_USER (name, email, password) VALUES ('Leonardo Pimentel', 'leonardo.pimentel@investinfo.com.br', '6666')
INSERT INTO TB_USER (name, email, password) VALUES ('Vanderlei Junior', 'vanderlei.junior@investinfo.com.br', '7777')

INSERT INTO TB_NEWS (description, LINK_NEWS, DATE_NEWS) VALUES ('a', 'ms', '10/10/10')
INSERT INTO TB_NEWS (description, LINK_NEWS, DATE_NEWS) VALUES ('b', 'ws', '11/10/10')
INSERT INTO TB_NEWS (description, LINK_NEWS, DATE_NEWS) VALUES ('c', 'wa', '12/10/10')
INSERT INTO TB_NEWS (description, LINK_NEWS, DATE_NEWS) VALUES ('d', 'ma', '13/10/10')
INSERT INTO TB_NEWS (description, LINK_NEWS, DATE_NEWS) VALUES ('e', 'am', '14/10/10')